// We are fetching all of this important information
// gracefully from backend, piece by piece, definitely
// not creating a HUGE constant that fills user's RAM.

const PAGES = {
  aardvark: '/pages/page-aardvark.html',
  ant: '/pages/page-ant.html',
  bear: '/pages/page-bear.html',
  bee: '/pages/page-bee.html',
  bird: '/pages/page-bird.html',
  butterfly: '/pages/page-butterfly.html',
  carp: '/pages/page-carp.html',
  cat: '/pages/page-cat.html',
  chicken: '/pages/page-chicken.html',
  dog: '/pages/page-dog.html',
  dolphin: '/pages/page-dolphin.html',
  donkey: '/pages/page-donkey.html',
  eagle: '/pages/page-eagle.html',
  elephant: '/pages/page-elephant.html',
  fish: '/pages/page-fish.html',
  frog: '/pages/page-frog.html',
  giraffe: '/pages/page-giraffe.html',
  goat: '/pages/page-goat.html',
  hamster: '/pages/page-hamster.html',
  hen: '/pages/page-hen.html',
  human: '/pages/page-human.html',
  insect: '/pages/page-insect.html',
  lion: '/pages/page-lion.html',
  lizard: '/pages/page-lizard.html',
  lynx: '/pages/page-lynx.html',
  mammal: '/pages/page-mammal.html',
  monkey: '/pages/page-monkey.html',
  narwhal: '/pages/page-narwhal.html',
  octopus: '/pages/page-octopus.html',
  otter: '/pages/page-otter.html',
  owl: '/pages/page-owl.html',
  ox: '/pages/page-ox.html',
  panda: '/pages/page-panda.html',
  penguin: '/pages/page-penguin.html',
  pig: '/pages/page-pig.html',
  rabbit: '/pages/page-rabbit.html',
  rinho: '/pages/page-rinho.html',
  shark: '/pages/page-shark.html',
  snail: '/pages/page-snail.html',
  snake: '/pages/page-snake.html',
  spider: '/pages/page-spider.html',
  tiger: '/pages/page-tiger.html',
  unicorn: '/pages/page-unicorn.html',
  vulture: '/pages/page-vulture.html',
  worm: '/pages/page-worm.html',
  zebra: '/pages/page-zebra.html',
};

// This should not exist, this information should be generated
// and stored in backend with some kind of analytics and/or
// machine learning enabled.
const NEXT_PAGE_MAP = {
  [PAGES.aardvark]: PAGES.ant,
  [PAGES.ant]: PAGES.bear,
  [PAGES.bear]: PAGES.bee,
  [PAGES.bee]: PAGES.bird,
  [PAGES.bird]: PAGES.butterfly,
  [PAGES.butterfly]: PAGES.carp,
  [PAGES.carp]: PAGES.cat,
  [PAGES.cat]: PAGES.chicken,
  [PAGES.chicken]: PAGES.dog,
  [PAGES.dog]: PAGES.dolphin,
  [PAGES.dolphin]: PAGES.donkey,
  [PAGES.donkey]: PAGES.eagle,
  [PAGES.eagle]: PAGES.elephant,
  [PAGES.elephant]: PAGES.fish,
  [PAGES.fish]: PAGES.frog,
  [PAGES.frog]: PAGES.giraffe,
  [PAGES.giraffe]: PAGES.goat,
  [PAGES.goat]: PAGES.hamster,
  [PAGES.hamster]: PAGES.hen,
  [PAGES.hen]: PAGES.human,
  [PAGES.human]: PAGES.insect,
  [PAGES.insect]: PAGES.lion,
  [PAGES.lion]: PAGES.lizard,
  [PAGES.lizard]: PAGES.lynx,
  [PAGES.lynx]: PAGES.mammal,
  [PAGES.mammal]: PAGES.monkey,
  [PAGES.monkey]: PAGES.narwhal,
  [PAGES.narwhal]: PAGES.octopus,
  [PAGES.octopus]: PAGES.otter,
  [PAGES.otter]: PAGES.owl,
  [PAGES.owl]: PAGES.ox,
  [PAGES.ox]: PAGES.panda,
  [PAGES.panda]: PAGES.penguin,
  [PAGES.penguin]: PAGES.pig,
  [PAGES.pig]: PAGES.rabbit,
  [PAGES.rabbit]: PAGES.rinho,
  [PAGES.rinho]: PAGES.shark,
  [PAGES.shark]: PAGES.snail,
  [PAGES.snail]: PAGES.snake,
  [PAGES.snake]: PAGES.spider,
  [PAGES.spider]: PAGES.tiger,
  [PAGES.tiger]: PAGES.unicorn,
  [PAGES.unicorn]: PAGES.vulture,
  [PAGES.vulture]: PAGES.worm,
  [PAGES.worm]: PAGES.zebra,
  [PAGES.zebra]: PAGES.ant,
};
